### ISSUE TITLE
LibCST transformer

### ISSUE THREAD

**Issue by zsol** [nathro/AutoTransform#12]
Hey @nathro, interesting project :wink: 
I maintain [libcst](https://github.com/instagram/libcst) so I _might_ be biased but it seems like having a transformer that applies a LibCST codemod would be a great fit.
Let me know if this sounds interesting!

**Comment by nathro** [comment]
Yup, that sounds like a perfect component, heh. I was looking for something like that for python (I'm familiar with equivalents in other languages). I'm gonna be returning my full attention to soon (potentially with some support), I'd love to take a look at libcst and figure out what an easy transformer to use for it looks like. Happy to chat if you want as well.

Out of curiosity, how did you stumble on this project?

**Comment by zsol** [comment]
> I'm gonna be returning my full attention to this soon (potentially with some support)

Exciting!

> I'd love to take a look at libcst and figure out what an easy transformer to use for it looks like. Happy to chat if you want as well.

Sure thing! I might put up a basic PR in a few weeks if I get the itch on a weekend. Happy to chat too, if we can find a time. Feel free to shoot me an email to my personal address.

> Out of curiosity, how did you stumble on this project?

@w-shackleton might have posted about it internally :)

**Comment by nathro** [comment]
@zsol I'm back to this stuff and have started building out components. Mind giving some pointers on how I might integrate a libCST transformer? Or if you want to make a PR that would be awesome too.

Basically just need the hook where I could pass something files/data and invoke libCST to make the changes.

**Comment by zsol** [comment]
To implement the single transformer API, we'll need to specify a specific libcst codemod class's fully qualified name (this would always be an input parameter), then instantiate the class and use `libcst.codemod.transform_module(codemod_instance, input_source_string)`. The libcst CLI tool does something similar here: https://github.com/Instagram/LibCST/blob/0a8ae91d39caa6065f920f290c1195ab1c217a61/libcst/tool.py#L539

**Comment by nathro** [comment]
Thanks for the info, I expect I'll get to this on Monday :)

**Comment by nathro** [comment]
So, I went back and forth on this, but I actually decided not to add this. I think there's a bit of bloat that comes from adding every possible component to the library available here. I have added a ScriptTransformer which makes it trivial to invoke CLI based tools to do transforms, so that should make it easy for someone to use LibCST with AutoTransform. If you want to write a LibCST transformer, I'll approve it I guess though *shrug*.

**Comment by nathro** [comment]
So I came back to this and decided to add it. It's now in place as LibCSTTransformer.

**Comment by zsol** [comment]
What made you change your mind?

**Comment by AutoTransform** [comment]
As I thought more about other languages (i.e. Hack, JS, etc...) I decided rather than rely on the ScriptTransformer for everything having a component for each language would steer people in the right direction and simplify the experience, which would be worth the bloat.

Basically, relying on ScriptTransformer was just going to make things too cumbersome for every language, so having a pattern would just end up being better. Also, with how I changed the way components are loaded, we don't have to load every component's module every time we do anything, so that reduces things a bit as well.

**Comment by nathro** [comment]
As I thought more about other languages (i.e. Hack, JS, etc...) I decided rather than rely on the ScriptTransformer for everything having a component for each language would steer people in the right direction and simplify the experience, which would be worth the bloat.

Basically, relying on ScriptTransformer was just going to make things too cumbersome for every language, so having a pattern would just end up being better. Also, with how I changed the way components are loaded, we don't have to load every component's module every time we do anything, so that reduces things a bit as well.
